name: CI

on:
  push:
    branches:
      - main

jobs:
  scaledown:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: scale down
        uses: mikefarah/yq@master
      - name: changes values to 0 
        run: |
          bash scale_down.sh
        shell: bash
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: "devops@orderonline.id"
          author_name: "devops-bot"
          github_token: ${{ secrets.GH_TOKEN }}
          repository: "devops-orderonline/learn-argocd"
      