name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: "values.yaml"


  changes:
    runs-on: ubuntu-latest
    name: Test changed-files
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: scale down
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.replicaCount=1' ${{ matrix.paths }}
      - name: Commit report
        run: |
          git config --global user.name 'devops orderonline'
          git config --global user.email 'devops@orderonline.id'
          git add ${{ matrix.paths }}
          git commit -am "Scheduler Scale Down ${{ matrix.paths }}"
          git push

  # push: 
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   steps: 
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
  #   - name: Commit report
  #     run: |
  #       git config --global user.name 'devops orderonline'
  #       git config --global user.email 'devops@orderonline.id'
  #       git add .
  #       git commit -am "Scheduler Scale Down"
  #       git push
      