name: CI

on:
  push:
    branches:
      - main

# ------------------------------------------------------------------------------------------------------------
# Event `push`: Compare the preceding commit -> to the current commit of the main branch.
# Event `pull_request`: Compare the last commit of main -> to the current commit of a Pull Request branch.
# ------------------------------------------------------------------------------------------------------------

permissions:
  contents: write

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: "values.yaml"
  changes:
    runs-on: ubuntu-latest
    name: Test changed-files
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    steps:
      - name: scale down
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.replicaCount=0' ${{ matrix.paths }}

  
  push: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
    - name: Commit report
      run: |
        git config --global user.name 'devops orderonline'
        git config --global user.email 'devops@orderonline.id'
        git add .
        git commit -am "Scheduler Scale Down"
        git push
      